[package]
name = "strips_visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
game_engine = { git = "https://github.com/Grigorii-M/game_engine.git"}
